services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "${DOMAINS:-localhost -> http://app-web:3000}"
      STAGE: "${STAGE:-local}"
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - app-web
    profiles:
      - production

  app-db:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: always
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB:-app_${RAILS_ENV:-development}} -U ${POSTGRES_USER:-postgres}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  app-web:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    command: bash -c "bundle install && bundle exec rails db:prepare && if [ \"$RAILS_ENV\" = \"production\" ]; then bundle exec rails assets:precompile; fi && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p ${PORT:-3000}"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    env_file:
      - .env
    expose:
      - "${PORT:-3000}"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      app-db:
        condition: service_healthy
volumes:
  bundle_data:
  postgresql_data:
  node_modules:
  https-portal-data:
