networks:
  app-network:
    external: true
    name: musicbrainz-docker_app-network

services:
  app-db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    expose:
      - "5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      app-db:
        condition: service_healthy
volumes:
  bundle_data:
  postgresql_data:
  node_modules:
